<?php
declare(strict_types=1);session_start();require_once __DIR__.'/manager_payout_common.php';
header('Cache-Control: no-store');header('X-Frame-Options: DENY');
if(!empty($_SESSION['_imp'])||!empty($_SESSION['_manager_edit'])||!(($_SESSION['is_admin']??false)||($_SESSION['ID_OK']??null)==1)){http_response_code(403);exit('사이트 관리자 계정으로 로그인해 주세요.');}
if(empty($_SESSION['csrf']))$_SESSION['csrf']=bin2hex(random_bytes(24));
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
 try{if(!is_string($_POST['csrf']??null)||!hash_equals($_SESSION['csrf'],$_POST['csrf']))throw new RuntimeException('새로고침 후 다시 시도해 주세요.');
 if(($_POST['decision']??'')==='paid'&&($_POST['sent']??'')!=='1')throw new RuntimeException('실제 송금 완료 여부를 확인해 주세요.');
 mp_process((string)($_SESSION['member_id']??'site-admin'),(string)($_POST['id']??''),(string)($_POST['decision']??''),trim((string)($_POST['note']??'')));$_SESSION['payout_admin_notice']='처리했습니다.';
 }catch(Throwable $e){$_SESSION['payout_admin_notice']=$e->getMessage();}
 header('Location: /admin_manager_payouts.php',true,303);exit;
}
$members=mg_members();$state=mg_read(mg_state_file());$rows=array_values($state['payouts']??[]);usort($rows,fn($a,$b)=>(($a['status']!=='pending')<=>($b['status']!=='pending'))?:strcmp($b['at'],$a['at']));
$totals=['pending'=>0,'paid'=>0,'rejected'=>0];$pendingAmount=0;
foreach($rows as $r){$totals[$r['status']]++;if($r['status']==='pending')$pendingAmount+=(int)$r['amount'];}

$managerRows=[];$summary=['held'=>0,'available'=>0,'pending'=>0,'paid'=>0,'deficit'=>0];
$linked=[];foreach($members as $id=>$m){if(!is_array($m)||!mg_active($m,'building'))continue;$owner=mg_connection_manager($m,$members);if($owner!==''&&mg_link_status((string)$id,$m,$state)==='accepted')$linked[$owner]=($linked[$owner]??0)+1;}
foreach($members as $uid=>$m){
 if(!is_array($m)||($m['role']??'')!=='agency')continue;
 $b=mp_balance($state,(string)$uid,$m);$b['held']=max(0,$b['earned']-$b['paid']);
 foreach($summary as $key=>$_)$summary[$key]+=$b[$key];
 $account=$state['payout_accounts'][mp_account_key((string)$uid,$m)]??null;
 $managerRows[]=['uid'=>(string)$uid,'name'=>(string)($m['nickname']??$uid),'code'=>(string)($m['manager_code']??''),'created'=>(string)($m['created']??''),'status'=>(string)($m['status']??'active'),'clients'=>$linked[$uid]??0,'balance'=>$b,'account'=>$account];
}
usort($managerRows,fn($a,$b)=>strcmp($b['created'],$a['created']));
?><!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>매니저 · 코인 관리</title>
<style>body{font:14px/1.7 system-ui;background:#f5f7fb;color:#25354b;margin:0}main{max-width:960px;margin:30px auto;padding:20px}article{background:#fff;border:1px solid #e1e6ef;border-radius:12px;padding:22px;margin:16px 0}h1{font-size:24px}input,button{font:inherit;padding:9px;border:1px solid #ccd5e2;border-radius:7px}button{cursor:pointer}label{display:block;margin:10px 0}.warn{color:#b45309}small{color:#64748b}.note{white-space:pre-wrap}
.top{display:flex;align-items:center;justify-content:space-between;gap:15px}h1{margin:10px 0}.subtitle{color:#64748b}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin:22px 0}.stat{background:#fff;border:1px solid #e2e8f0;border-radius:12px;padding:18px}.stat span{display:block;font-size:12px;color:#64748b}.stat b{font-size:25px;display:block;margin-top:5px}.filters{display:flex;gap:10px;flex-wrap:wrap;margin:18px 0}.filters input{flex:1;min-width:180px;background:white}.filters select{padding:10px;border:1px solid #ccd5e2;border-radius:8px;font:inherit;background:white}.payout-head{display:flex;justify-content:space-between;align-items:start;gap:12px}.payout-head strong{font-size:18px}.badge{font-size:12px;background:#eef2ff;color:#5146b8;border-radius:20px;padding:5px 10px}.account-box{background:#f7f9fc;border-radius:8px;padding:12px 14px;line-height:1.9}.code{font-size:12px;color:#718096}button[value=paid]{background:#5146cf;color:white;border-color:#5146cf}button:disabled{opacity:.4;cursor:default}input[name=note]{width:min(90%,420px)}[hidden]{display:none!important}@media(max-width:600px){main{margin:0;padding:16px}.stats{grid-template-columns:1fr}.stat{padding:12px}.stat b{font-size:21px}.payout-head{flex-wrap:wrap}}

main{max-width:1280px}h2{font-size:19px;margin:32px 0 12px}.table-wrap{overflow:auto;border:1px solid #e1e6ef;border-radius:12px;background:white}table{border-collapse:collapse;width:100%;min-width:950px;text-align:left}th{font-size:12px;font-weight:600;color:#64748b;background:#f8fafc}td,th{padding:14px 16px;border-bottom:1px solid #eef1f5}td{font-size:13px}td small{display:block;margin-top:4px}td button{padding:5px 8px;font-size:11px;background:#f6f5ff;color:#5146b8}tbody tr:hover{background:#fafbfe}
</style><main><a href="/clients_mini.php">매니저 화면</a><h1>매니저 · 코인 관리</h1><p class="subtitle">가입 현황부터 코인 잔액, 출금 처리까지 한곳에서 확인하세요.</p><p>1코인 = 19,000원 · 실제 송금은 은행에서 직접 진행하세요. 이 화면의 지급 완료 버튼은 송금을 실행하지 않습니다.</p>
<?php if(isset($_SESSION['payout_admin_notice'])): ?><p role="status"><?=mg_e($_SESSION['payout_admin_notice'])?></p><?php unset($_SESSION['payout_admin_notice']);endif;?>

<h2>전체 매니저 현황</h2>
<div class="stats overview-stats"><div class="stat"><span>등록된 매니저</span><b><?=number_format(count($managerRows))?>명</b></div><div class="stat"><span>전체 보유 코인 · 출금 신청 중 포함</span><b><?=number_format($summary['held'])?>개</b><small>정상 적립 − 지급 완료, 매니저별 0 이상</small></div><div class="stat"><span>출금 가능 코인</span><b><?=number_format($summary['available'])?>개</b><small><?=number_format($summary['available']*MP_RATE)?>원 상당</small></div></div>
<p class="subtitle">현재 회원 데이터에 등록된 모든 매니저를 집계합니다. 환불 회수 코인은 적립에서 제외하며, 실제 송금액은 출금 신청의 확정 금액을 확인하세요.</p>
<?php if($summary['deficit']):?><p class="warn">환불 등에 따른 정산 부족 <?=number_format($summary['deficit'])?>코인 — ‘정산 확인 필요’ 필터에서 확인하세요.</p><?php endif;?>
<div class="filters"><input id="manager-search" type="search" aria-label="가입 매니저 검색" placeholder="매니저 이름 · 아이디 · 코드 검색"><select id="manager-filter" aria-label="매니저 현황 필터"><option value="all">전체 매니저</option><option value="pending">출금 신청 중</option><option value="balance">출금 가능 코인 보유</option><option value="missing">계좌 미등록</option><option value="deficit">정산 확인 필요</option></select><select id="manager-sort" aria-label="매니저 정렬"><option value="new">최근 가입순</option><option value="balance">보유 코인순</option><option value="clients">담당 유저순</option></select></div><p id="manager-count" role="status"></p>
<div class="table-wrap"><table><thead><tr><th>매니저 / 코드</th><th>가입일 / 상태</th><th>담당 유저</th><th>보유 코인</th><th>출금 가능</th><th>신청 중</th><th>지급 완료</th><th>계좌 / 내역</th></tr></thead><tbody id="manager-table">
<?php foreach($managerRows as $i=>$m):$b=$m['balance'];?><tr data-manager-row data-order="<?=$i?>" data-search="<?=mg_e($m['uid'].' '.$m['name'].' '.$m['code'])?>" data-held="<?=$b['held']?>" data-clients="<?=$m['clients']?>" data-pending="<?=$b['pending']?>" data-available="<?=$b['available']?>" data-deficit="<?=$b['deficit']?>" data-account="<?=$m['account']?'1':'0'?>"><td><strong><?=mg_e($m['name'])?></strong><small><?=mg_e($m['uid'])?><br><?=mg_e($m['code']?:'코드 미발급')?></small></td><td><?=mg_e(substr($m['created'],0,10)?:'미등록')?><small><?=mg_e(['active'=>'활성','pending'=>'승인 대기','blocked'=>'차단','suspended'=>'정지','deleted'=>'탈퇴'][$m['status']]??$m['status'])?></small></td><td><?=$m['clients']?>명</td><td><b><?=number_format($b['held'])?></b>개</td><td><?=number_format($b['available'])?>개<?php if($b['deficit']):?><small class="warn">정산 부족 <?=$b['deficit']?>개</small><?php endif;?></td><td><?=number_format($b['pending'])?>개</td><td><?=number_format($b['paid'])?>개</td><td><small><?=$m['account']?'등록됨':'미등록'?></small><button type="button" data-manager-payouts="<?=mg_e($m['uid'])?>">출금 내역</button></td></tr><?php endforeach;?></tbody></table></div><p id="manager-empty" hidden>해당 조건의 매니저가 없습니다.</p>
<h2 id="payout-section">출금 신청 처리</h2><p class="subtitle">아래 출금 통계는 보관된 전체 신청 내역 기준입니다.</p>
<div class="stats"><div class="stat"><span>처리 대기</span><b><?=$totals['pending']?>건</b></div><div class="stat"><span>대기 신청 금액</span><b><?=number_format($pendingAmount)?>원</b></div><div class="stat"><span>지급 완료</span><b><?=$totals['paid']?>건</b></div></div>
<div class="filters"><input type="search" id="payout-search" aria-label="매니저 검색" placeholder="매니저 이름 · 아이디 · 신청번호 검색"><select id="payout-filter" aria-label="처리 상태"><option value="pending">처리 대기</option><option value="all">전체 신청</option><option value="paid">지급 완료</option><option value="rejected">반려</option></select></div><p id="payout-result" role="status"></p>
<?php if(!$rows): ?><p>출금 신청이 없습니다.</p><?php endif;?>
<?php foreach($rows as $r):$pending=$r['status']==='pending';$me=$members[$r['manager']]??[];$blocked=!mg_active($me,'agency')||!mp_owned($r,$r['manager'],$me)||mp_balance($state,$r['manager'],$me)['deficit']>0;?>
<article data-manager="<?=mg_e($r['manager'])?>" data-payout-row data-status="<?=mg_e($r['status'])?>" data-search="<?=mg_e($r['name'].' '.$r['manager'].' '.$r['id'].' '.($me['nickname']??''))?>"><div class="payout-head"><div><strong><?=mg_e($r['name'])?> 매니저</strong><div class="code">아이디 <?=mg_e($r['manager'])?><?php if(mp_owned($r,$r['manager'],$me)&&!empty($me['manager_code'])): ?> · 코드 <?=mg_e($me['manager_code'])?><?php endif;?></div></div><span class="badge"><?=mg_e(['pending'=>'처리 대기','paid'=>'지급 완료','rejected'=>'반려'][$r['status']])?></span></div><p><?=number_format($r['coins'])?>코인 / <b><?=number_format($r['amount'])?>원</b> · <?=mg_e(['pending'=>'신청 대기','paid'=>'지급 완료','rejected'=>'반려'][$r['status']])?></p><small>신청 <?=mg_e($r['at'])?> · 신청번호 <?=mg_e(substr($r['id'],0,12))?></small>
<p class="account-box">송금 계좌<br><?=mg_e($r['account']['bank'])?> / <?=mg_e($pending?$r['account']['number']:mp_mask($r['account']['number']))?> / 예금주 <?=mg_e($r['account']['holder'])?></p>
<?php if($pending): ?><?php if($blocked):?><p class="warn">회원 상태 또는 환불로 인한 코인 부족을 확인하세요. 지급 완료 처리가 차단됩니다.</p><?php endif;?>
<form method="post"><input type="hidden" name="csrf" value="<?=mg_e($_SESSION['csrf'])?>"><input type="hidden" name="id" value="<?=mg_e($r['id'])?>"><label>처리 메모 / 반려 사유 <input name="note" maxlength="200" placeholder="이체 확인번호 또는 반려 사유"></label><label><input type="checkbox" name="sent" value="1"> 위 계좌와 금액으로 실제 송금을 완료했습니다.</label><button name="decision" value="paid" <?=$blocked?'disabled':''?>>지급 완료 처리</button> <button name="decision" value="rejected">반려 · 코인 반환</button></form>
<?php else: ?><p><?=mg_e($r['processed_at']??'')?></p><p class="note"><?=mg_e($r['note'])?></p><?php endif;?></article><?php endforeach;?><p id="payout-empty" hidden>해당 조건의 출금 신청이 없습니다.</p></main><script>
(()=>{let exactManager=null;const input=document.getElementById('payout-search'),filter=document.getElementById('payout-filter'),rows=[...document.querySelectorAll('[data-payout-row]')];function apply(){let n=0;const q=input.value.trim().toLocaleLowerCase();for(const row of rows){row.hidden=!(filter.value==='all'||row.dataset.status===filter.value)||!row.dataset.search.toLocaleLowerCase().includes(q)||(exactManager!==null&&row.dataset.manager!==exactManager);if(!row.hidden)n++;}document.getElementById('payout-result').textContent=n+'건의 신청';document.getElementById('payout-empty').hidden=n>0;}input.addEventListener('input',()=>{exactManager=null;apply();});filter.addEventListener('change',apply);document.querySelectorAll('[data-manager-payouts]').forEach(b=>b.addEventListener('click',()=>{exactManager=b.dataset.managerPayouts;input.value=exactManager;filter.value='all';apply();document.getElementById('payout-section').scrollIntoView({behavior:'smooth'});}));apply();})();
</script><script>
(()=>{const input=document.getElementById('manager-search'),filter=document.getElementById('manager-filter'),sort=document.getElementById('manager-sort'),body=document.getElementById('manager-table'),rows=[...body.querySelectorAll('[data-manager-row]')];function apply(){const q=input.value.trim().toLocaleLowerCase();let n=0;rows.sort((a,b)=>sort.value==='new'?Number(a.dataset.order)-Number(b.dataset.order):Number(b.dataset[sort.value==='balance'?'held':'clients'])-Number(a.dataset[sort.value==='balance'?'held':'clients']));for(const row of rows){const d=row.dataset;const match=filter.value==='all'||(filter.value==='pending'&&Number(d.pending)>0)||(filter.value==='balance'&&Number(d.available)>0)||(filter.value==='missing'&&d.account==='0')||(filter.value==='deficit'&&Number(d.deficit)>0);row.hidden=!match||!d.search.toLocaleLowerCase().includes(q);body.append(row);if(!row.hidden)n++;}document.getElementById('manager-count').textContent=n+'명 / 전체 '+rows.length+'명';document.getElementById('manager-empty').hidden=n>0;}input.addEventListener('input',apply);filter.addEventListener('change',apply);sort.addEventListener('change',apply);apply();})();
</script></html>
