(()=>{
 if(!HOSTED)return;
 const d=document.createElement('dialog');d.className='bes-text-dialog';d.innerHTML='<header><div><small>말하듯 설명해서 그리기</small><h2>이 층은 어떻게 생겼나요?</h2></div><button type="button" data-close aria-label="닫기">×</button></header><p>방과 복도의 배치를 설명해 주세요. 위쪽·아래쪽은 화면 기준입니다.</p><div class="bes-text-examples"><button data-example="가운데 세로 복도가 있고 왼쪽에 사무실 세 개, 오른쪽에 창고 두 개가 있어. 출구는 아래쪽 가운데야. 문 위치는 아직 모르겠어.">사무실과 창고</button><button data-example="넓은 홀 하나와 오른쪽 위에 작은 관리실이 있어. 출입구는 아래쪽 중앙이야.">홀과 관리실</button><button data-example="가운데 가로 복도가 있고 위쪽에 교실 네 개, 아래쪽 오른편에 계단실이 있어. 문과 출구 위치는 직접 확인할게.">교실 배치</button></div><label>건물 내부 설명<textarea rows="4" maxlength="2000" placeholder="가운데 복도, 왼쪽 사무실 세 개…"></textarea></label><small>입력한 설명과 바닥 크기만 AI 서비스로 전송합니다.</small><div class="bes-text-controls"><button data-generate>설명으로 초안 만들기</button><span role="status"></span></div><section data-result hidden><svg viewBox="0 0 600 400" aria-label="배치 초안 미리보기" role="img"></svg><div data-questions></div><label class="bes-check"><input type="checkbox">대략적인 배치이며 실제 크기·문·출구·계단 연결을 확인해야 함을 이해했습니다.</label><button data-apply>현재 층에 적용하고 다듬기</button></section><p class="bes-text-footnote">현재 층만 변경합니다. 적용 전에는 저장된 도면이 바뀌지 않습니다. 설명을 고쳐 다시 만들거나, 적용 후 기존 도구로 수정할 수 있습니다.</p>';
 document.body.append(d);let draft=null,target=null,controller=null;
 const input=d.querySelector('textarea'),status=d.querySelector('[role=status]'),result=d.querySelector('[data-result]'),svg=d.querySelector('svg'),check=d.querySelector('[type=checkbox]');
 const b=document.createElement('button');b.type='button';b.textContent='설명으로 그리기';document.querySelector('.bes-editor-actions').prepend(b);
 function open(){target={f:viewF,w:GW,h:GH,map:serializeMap()};draft=null;result.hidden=true;check.checked=false;status.textContent='';d.showModal();input.focus();}window.bedOpen=open;b.onclick=open;
 const close=()=>{controller?.abort();controller=null;d.close();};d.querySelector('[data-close]').onclick=close;d.addEventListener('cancel',e=>{e.preventDefault();close();});
 d.querySelectorAll('[data-example]').forEach(b=>b.onclick=()=>{input.value=b.dataset.example;input.focus();});
 function node(tag,attrs,text){const n=document.createElementNS('http://www.w3.org/2000/svg',tag);for(const[k,v]of Object.entries(attrs))n.setAttribute(k,v);if(text)n.textContent=text;svg.append(n);return n;}
 function preview(){svg.replaceChildren();const scale=Math.min(560/target.w,340/target.h),x=20,y=20;node('rect',{x,y,width:target.w*scale,height:target.h*scale,fill:'#f6f9fc',stroke:'#405978','stroke-width':3});for(const r of draft.rooms){node('rect',{x:x+r.x*scale,y:y+r.y*scale,width:r.w*scale,height:r.h*scale,fill:r.kind==='stair'?'#d9edfa':'#e4eaff',stroke:'#6885ad','stroke-width':2});node('text',{x:x+(r.x+r.w/2)*scale,y:y+(r.y+r.h/2)*scale,'text-anchor':'middle','font-size':11,fill:'#29446b'},r.name);}for(const p of draft.doors)node('rect',{x:x+p.x*scale,y:y+p.y*scale,width:scale,height:scale,fill:p.kind==='exit'?'#00a579':'#ec9936'});const q=d.querySelector('[data-questions]');q.replaceChildren();for(const text of ['초안 확인: 방 크기는 추정치입니다. 녹색은 출구, 주황색은 문입니다.',...draft.questions]){const p=document.createElement('p');p.textContent=text;q.append(p);}result.hidden=false;check.checked=false;}
 d.querySelector('[data-generate]').onclick=async e=>{
  if(!input.value.trim()){status.textContent='방과 복도 배치를 먼저 설명해 주세요.';return;}
  const button=e.currentTarget;button.disabled=true;draft=null;result.hidden=true;status.textContent='배치 초안을 만들고 있습니다…';controller=new AbortController();const current=controller;
  try{const u=new URL(SAVE_URL,location.href);u.pathname=u.pathname.replace('building_evac.php','building_evac_draft.php');const r=await fetch(u,{method:'POST',signal:current.signal,body:new URLSearchParams({csrf:LIB_CSRF,message:input.value,width:target.w,height:target.h})});const j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||'초안을 만들지 못했습니다.');if(controller!==current||!d.open)return;draft=j.draft;preview();status.textContent='배치를 확인하고, 설명을 수정해 다시 만들 수도 있습니다.';}catch(e){if(e.name!=='AbortError')status.textContent=e.message;}finally{button.disabled=false;if(controller===current)controller=null;}
 };
 d.querySelector('[data-apply]').onclick=()=>{
  if(!draft||!draft.rooms.length){status.textContent='배치할 방이 없습니다. 설명을 보완해 주세요.';return;}if(!check.checked){status.textContent='확인 사항을 읽고 체크해 주세요.';return;}
  if(target.map!==serializeMap()||target.w!==GW||target.h!==GH){status.textContent='도면이 변경되었습니다. 창을 닫고 다시 만들어 주세요.';return;}
  if(!confirm('현재 층의 벽·방·문·계단과 안내 경로를 이 초안으로 교체할까요? 다른 층은 유지됩니다.'))return;
  const g=Array.from({length:GH},(_,y)=>Array.from({length:GW},(_,x)=>x===0||y===0||x===GW-1||y===GH-1?WALL:FLOOR));
  for(const r of draft.rooms)for(let y=r.y;y<r.y+r.h;y++)for(let x=r.x;x<r.x+r.w;x++)g[y][x]=x===r.x||y===r.y||x===r.x+r.w-1||y===r.y+r.h-1?WALL:r.kind==='stair'?STAIR:FLOOR;
  for(const p of draft.doors)g[p.y][p.x]=p.kind==='exit'?EXIT:DOOR;
  snapshot();grids[target.f]=g;window.besRoutes=(window.besRoutes||[]).filter(r=>r.floor!==target.f);window.besRoomLabels=(window.besRoomLabels||[]).filter(r=>r.floor!==target.f).concat(draft.rooms.map(r=>({name:r.name,floor:target.f,x:r.x+r.w/2,y:r.y+r.h/2})));
  customMapText=serializeMap();viewF=target.f;reset();showPane(true);runDiagnostics();renderStairCfg();autoSave();close();
 };
 window.besRoomLabels=JSON.parse(HOST_SCN||'{}').room_labels||[];
 const original=window.besDrawRoutes;window.besDrawRoutes=()=>{original?.();ctx.save();ctx.setTransform(1,0,0,1,0,0);ctx.translate(PLAN_PAD,PLAN_PAD);ctx.font='11px system-ui';ctx.textAlign='center';for(const l of window.besRoomLabels){if(l.floor!==viewF||l.x>=GW||l.y>=GH)continue;const w=ctx.measureText(l.name).width;ctx.fillStyle='#f4f8ffdd';ctx.fillRect(l.x*CELL-w/2-4,l.y*CELL-12,w+8,17);ctx.fillStyle='#264566';ctx.fillText(l.name,l.x*CELL,l.y*CELL);}ctx.restore();};
 const clear=document.createElement('button');clear.type='button';clear.textContent='현재 층 방 이름 지우기';clear.onclick=()=>{window.besRoomLabels=window.besRoomLabels.filter(l=>l.floor!==viewF);autoSave();};document.querySelector('#paneEdit .bes-precision').append(clear);
})();
