(()=>{
 const script=document.currentScript,ownUid=script?.dataset.uid||'';
 let dialog=null,currentUid='',csrf='',items=[],busy=false,version=0,opener=null,previousOverflow='';
 const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
 const localDate=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date()).replace(' ','T');
 const uuid=()=>Array.from(crypto.getRandomValues(new Uint8Array(16)),b=>b.toString(16).padStart(2,'0')).join('');
 async function request(uid,payload){const res=await fetch('/false_alarm_api.php?uid='+encodeURIComponent(uid),{credentials:'same-origin',cache:'no-store',...(payload?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}:{})});let data;try{data=await res.json();}catch{throw Error('로그인 상태와 서버 연결을 확인해 주세요.');}if(!res.ok||!data.ok)throw Error(data.error||'기록을 불러오지 못했습니다.');return data;}
 function count(data){document.querySelectorAll('[data-false-alarm-count]').forEach(n=>{if(n.dataset.falseAlarmCount===currentUid)n.textContent=data.count+'건';});}
 function render(data){items=data.rows;csrf=data.csrf;count(data);const list=dialog.querySelector('.fa-list');list.replaceChildren();dialog.querySelector('.fa-total').textContent='기록 '+data.count+'건';if(!items.length)list.append(el('p','아직 기록이 없습니다. 발생 내용과 조치 사항을 남겨 주세요.','fa-empty'));
 items.forEach(row=>{const card=el('article',undefined,'fa-record');const head=el('div',undefined,'fa-record-head');head.append(el('strong',row.occurred_at.replace('T',' ')),el('span',row.status,'fa-state'));card.append(head,el('h4',row.location));const details=el('dl');for(const [title,text] of [['추정 원인',row.cause||'미확인'],['조치 내용',row.action]]){details.append(el('dt',title),el('dd',text));}card.append(details,el('p','작성: '+row.created_name+' · 최근 수정: '+row.updated_name+' / '+new Date(row.updated_at).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'}),'fa-by'));const edit=el('button','수정','fa-edit');edit.type='button';edit.onclick=()=>{const form=dialog.querySelector('form');if(dirty()&&!confirm('작성 중인 내용을 버리고 이 기록을 수정할까요?'))return;for(const k of ['id','revision','occurred_at','location','cause','action','status'])form.elements[k].value=row[k];dialog.querySelector('.fa-form-title').textContent='기록 수정';form.dataset.initial=formSnapshot(form);form.scrollIntoView({block:'start',behavior:'smooth'});};card.append(edit);list.append(card);});
 }
 function formSnapshot(form){return JSON.stringify(['occurred_at','location','cause','action','status'].map(name=>form.elements[name].value));}
 function dirty(){const form=dialog?.querySelector('form');return form&&formSnapshot(form)!==form.dataset.initial;}
 function reset(){const f=dialog.querySelector('form');f.reset();f.elements.id.value=uuid();f.elements.revision.value='0';f.elements.occurred_at.value=localDate();f.dataset.initial=formSnapshot(f);dialog.querySelector('.fa-form-title').textContent='새 기록 작성';}
 async function load(){const v=++version,uid=currentUid;dialog.querySelector('.fa-message').textContent='불러오는 중…';try{const data=await request(uid);if(v!==version||!dialog.open)return;render(data);dialog.querySelector('fieldset').disabled=false;dialog.querySelector('.fa-message').textContent='';}catch(e){if(v===version)dialog.querySelector('.fa-message').textContent=e.message;}}
 function close(){if(busy)return;if(dirty()&&!confirm('작성 중인 내용을 저장하지 않고 닫을까요?'))return;dialog.close();}
 function openPrintPreview(trigger){
  if(document.getElementById('fa-print-preview'))return;
  const preview=el('dialog',undefined,'fa-print-dialog');preview.id='fa-print-preview';preview.setAttribute('aria-labelledby','fa-print-preview-title');
  const head=el('header',undefined,'fa-print-head');const title=el('h2','비화재보 기록 · 인쇄 / PDF');title.id='fa-print-preview-title';
  const closeButton=el('button','닫기 ×','fa-print-close');closeButton.type='button';closeButton.setAttribute('aria-label','인쇄 미리보기 닫기');closeButton.onclick=()=>preview.close();head.append(title,closeButton);
  const frame=document.createElement('iframe');frame.title='비화재보 기록 인쇄 미리보기';
  preview.append(head,frame);document.body.append(preview);
  preview.addEventListener('close',()=>{frame.src='about:blank';preview.remove();if(trigger?.isConnected)trigger.focus({preventScroll:true});},{once:true});
  preview.showModal();frame.src='/false_alarm_print.php?uid='+encodeURIComponent(currentUid);closeButton.focus({preventScroll:true});
 }
 function init(){if(dialog)return;dialog=el('dialog',undefined,'fa-dialog');dialog.setAttribute('aria-labelledby','fa-title');dialog.innerHTML='<header class="fa-head"><div><small>현장 기록</small><h2 id="fa-title">비화재보 기록</h2></div><button type="button" class="fa-close" aria-label="비화재보 기록 닫기">×</button></header><div class="fa-body"><p class="fa-message" role="status"></p><form><fieldset disabled><h3 class="fa-form-title">새 기록 작성</h3><input type="hidden" name="id"><input type="hidden" name="revision"><div class="fa-fields"><label>발생일시<input name="occurred_at" type="datetime-local" required></label><label>처리 상태<select name="status"><option>확인 중</option><option>조치 중</option><option>조치 완료</option></select></label></div><label>발생 위치<input name="location" maxlength="120" placeholder="예: 본관 2층 복도 감지기" required></label><label>추정 원인<input name="cause" maxlength="1000" placeholder="확인되지 않았다면 비워두세요"></label><label>조치 내용<textarea name="action" maxlength="2000" rows="3" placeholder="확인한 상황과 조치 내용을 적어주세요." required></textarea></label><div class="fa-actions"><button type="button" class="fa-reset">새로 작성</button><button type="submit" class="fa-save">기록 저장</button></div></fieldset></form><div class="fa-history-head"><h3 class="fa-total">기록</h3><div><button type="button" class="fa-print">인쇄 / PDF</button> <button type="button" class="fa-refresh">새로고침</button></div></div><div class="fa-list"></div></div>';
 document.body.append(dialog);dialog.querySelector('.fa-close').onclick=close;dialog.addEventListener('cancel',e=>{e.preventDefault();close();});dialog.addEventListener('close',()=>{version++;document.body.style.overflow=previousOverflow;opener?.focus({preventScroll:true});});dialog.querySelector('.fa-reset').onclick=()=>{if(!dirty()||confirm('작성 중인 내용을 지우고 새 기록을 작성할까요?'))reset();};dialog.querySelector('.fa-refresh').onclick=load;
 dialog.querySelector('.fa-print').onclick=()=>{if(busy)return;if(!items.length){dialog.querySelector('.fa-message').textContent='인쇄할 저장된 기록이 없습니다.';return;}if(dirty()&&!confirm('작성 중인 내용은 제외하고 저장된 기록만 인쇄할까요?'))return;openPrintPreview(dialog.querySelector('.fa-print'));};
 dialog.querySelector('form').onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;const f=e.currentTarget,payload=Object.fromEntries(new FormData(f));payload.revision=Number(payload.revision);payload.csrf=csrf;dialog.querySelector('fieldset').disabled=true;dialog.querySelector('.fa-refresh').disabled=true;try{const data=await request(currentUid,payload);render(data);reset();dialog.querySelector('.fa-message').textContent='저장했습니다. 해당 건물의 기록에 반영되었습니다.';}catch(error){dialog.querySelector('.fa-message').textContent=error.message;}finally{busy=false;dialog.querySelector('fieldset').disabled=false;dialog.querySelector('.fa-refresh').disabled=false;}};
 }
 window.openFalseAlarm=async(uid,trigger)=>{if(dialog?.open)return;init();opener=trigger||document.activeElement;currentUid=uid||ownUid;csrf='';items=[];dialog.querySelector('.fa-list').replaceChildren();dialog.querySelector('.fa-total').textContent='기록';dialog.querySelector('fieldset').disabled=true;reset();previousOverflow=document.body.style.overflow;dialog.showModal();document.body.style.overflow='hidden';dialog.querySelector('.fa-close').focus({preventScroll:true});await load();};
 document.addEventListener('click',e=>{const b=e.target.closest('[data-false-alarm-open]');if(b){e.preventDefault();window.openFalseAlarm(b.dataset.falseAlarmOpen||ownUid,b);}});
 async function refreshCount(){if(!ownUid||document.hidden||busy)return;const stamp=version;try{const data=await request(ownUid);if(busy||stamp!==version)return;document.querySelectorAll('[data-false-alarm-count]').forEach(n=>{if(n.dataset.falseAlarmCount===ownUid)n.textContent=data.count+'건';});if(dialog?.open&&!busy&&currentUid===ownUid)render(data);}catch{}}
 refreshCount();setInterval(refreshCount,30000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refreshCount();});window.addEventListener('focus',refreshCount);
})();
