(()=>{
 const dialog=document.getElementById('fire-manager-board'),trigger=document.querySelector('[data-fmb-open]');if(!dialog||!trigger)return;
 const data=JSON.parse(document.getElementById('fmb-data').textContent),frame=dialog.querySelector('iframe'),select=dialog.querySelector('[data-fmb-manager]');
 const fields=Object.fromEntries([...dialog.querySelectorAll('[data-fmb-field]')].map(el=>[el.dataset.fmbField,el]));
 const status=dialog.querySelector('[data-fmb-status]');let previousOverflow='',ready=false;
 (data.managers.length?data.managers:[{name:'직접 입력'}]).forEach((m,i)=>{const o=document.createElement('option');o.value=i;o.textContent=m.name+(m.type?' · '+m.type:'');select.append(o);});
 const template=`<!doctype html><html lang="ko"><head><meta charset="utf-8"><title>소방안전관리자 현황표</title><style>
 @page{size:A4 landscape;margin:0}*{box-sizing:border-box}html,body{margin:0}body{background:#edf1f6;font-family:'NanumBarunGothic','나눔바른고딕','Apple SD Gothic Neo',sans-serif}.sheet{width:297mm;height:210mm;background:rgb(242,242,242);display:flex;flex-direction:column;border:1px solid #1c3d62;transform-origin:top left;overflow:hidden}.top,.bottom{background:rgb(28,61,98);color:#fff;font-family:'NanumGothic','나눔고딕',sans-serif;font-weight:800}.top{padding:4.95mm 6.36mm;min-height:26.87mm;display:flex;align-items:center;gap:2.83mm;flex-wrap:wrap}.top h1{font-size:32.53pt;margin:0;white-space:nowrap}.target{font-size:24.75pt;overflow-wrap:anywhere}.content{flex:1;padding:9.9mm 7.07mm;display:flex;flex-direction:column;justify-content:space-around;gap:3.54mm;font-size:21.21pt;color:#000}.content p{margin:0;overflow-wrap:anywhere}.appointment{margin-left:4.95mm}.legal{font-size:16.97pt}.bottom{padding:4.24mm 8.49mm;font-size:21.21pt;min-height:17.68mm;overflow-wrap:anywhere}@media print{html,body{width:297mm;height:210mm;background:white}.sheet{transform:none!important;print-color-adjust:exact;-webkit-print-color-adjust:exact}}
 </style></head><body><article class="sheet"><header class="top"><h1>소방안전관리자 현황표</h1><span class="target">(대상명: <b data-value="name"></b>)</span></header><main class="content"><p>이 건축물의 소방안전관리자는 다음과 같습니다.</p><p>□ 소방안전관리자: <b data-value="manager"></b><span class="appointment">(선임일자: <span data-value="appt"></span>)</span></p><p>□ 소방안전관리대상물 등급: <b data-value="grade"></b></p><p>□ 소방안전관리자 근무 위치(화재 수신기 위치): <span data-value="location"></span></p><p class="legal">「화재의 예방 및 안전관리에 관한 법률」 제26조제1항에 따라 이 표지를 붙입니다.</p></main><footer class="bottom">소방안전관리자 연락처: <span data-value="tel"></span></footer></article></body></html>`;
 function resize(){if(!ready||!dialog.open)return;const sheet=frame.contentDocument.querySelector('.sheet');sheet.style.transform='scale('+Math.min(frame.clientWidth/sheet.offsetWidth,frame.clientHeight/sheet.offsetHeight,1)+')';}
 function render(){if(!ready)return;for(const [key,input] of Object.entries(fields)){let value=input.value.trim();if(key==='appt'&&value)value=value.replace(/^(\d{4})-(\d{2})-(\d{2})$/,'$1년 $2월 $3일');frame.contentDocument.querySelector('[data-value="'+key+'"]').textContent=value||'________________';}resize();}
 function manager(){const m=data.managers[Number(select.value)]||{};fields.manager.value=m.name||'';fields.tel.value=m.tel||'';const date=String(m.appt||'').trim().replace(/[./]/g,'-');fields.appt.value=/^\d{4}-\d{2}-\d{2}$/.test(date)?date:'';render();}
 fields.name.value=data.name;fields.grade.value=data.grade;select.value=Math.max(0,data.managers.findIndex(m=>String(m.type||'').startsWith('주')));manager();
 frame.addEventListener('load',()=>{ready=true;render();});frame.srcdoc=template;
 trigger.addEventListener('click',()=>{previousOverflow=document.body.style.overflow;document.body.style.overflow='hidden';dialog.showModal();render();dialog.querySelector('[data-fmb-close]').focus();});
 dialog.querySelector('[data-fmb-close]').onclick=()=>dialog.close();dialog.addEventListener('close',()=>{document.body.style.overflow=previousOverflow;trigger.focus({preventScroll:true});});
 select.addEventListener('change',manager);Object.values(fields).forEach(el=>el.addEventListener('input',()=>{status.textContent='';render();}));
 new ResizeObserver(resize).observe(frame);
 dialog.querySelector('[data-fmb-print]').onclick=()=>{const missing=Object.values(fields).find(el=>!el.value.trim());if(missing){status.textContent='비어 있는 항목을 입력한 뒤 인쇄해 주세요.';missing.focus();return;}if(!ready)return;render();const sheet=frame.contentDocument.querySelector('.sheet');if(sheet.scrollHeight>sheet.clientHeight||sheet.scrollWidth>sheet.clientWidth){status.textContent='내용이 용지를 벗어납니다. 대상명이나 근무 위치를 짧게 정리해 주세요.';return;}frame.contentWindow.focus();frame.contentWindow.print();};
})();
