window.managerDraftDuplicateChoice=function(matches){return new Promise(resolve=>{
 const d=document.createElement('dialog');d.style.cssText='width:min(470px,calc(100vw - 32px));max-height:85vh;overflow:auto;margin:auto;padding:24px;border:1px solid #dce5ef;border-radius:18px;color:#263b55;background:white;box-shadow:0 20px 65px #18344c30;font-family:inherit';
 const title=document.createElement('h3');title.textContent='이미 등록한 건물이에요';title.style.cssText='font-size:19px;margin:0 0 8px';
 const note=document.createElement('p');note.textContent='같은 주소의 건물이 있습니다. 기존 정보를 열거나, 다른 동·구역이면 구분해서 등록하세요.';note.style.cssText='color:#748499;font-size:13px;line-height:1.7';d.append(title,note);
 let settled=false;function finish(v){if(settled)return;settled=true;d.close();d.remove();resolve(v);}
 function button(text,fn){const b=document.createElement('button');b.type='button';b.textContent=text;b.style.cssText='padding:10px 13px;border:1px solid #d6e2ef;border-radius:9px;background:#f2f6fc;color:#28558b;font:600 13px system-ui;cursor:pointer';b.onclick=fn;return b;}
 matches.forEach(m=>{const card=document.createElement('div');card.style.cssText='padding:14px;border:1px solid #e0e7ef;border-radius:12px;margin:12px 0';const n=document.createElement('strong');n.textContent=m.name;const a=document.createElement('p');a.textContent=[m.address,m.dong,m.area].filter(Boolean).join(' · ');a.style.cssText='font-size:12px;color:#718297;line-height:1.6';card.append(n,a,button('기존 건물 열기',()=>finish({url:m.url})));d.append(card);});
 const form=document.createElement('form');form.hidden=true;const label=document.createElement('label');label.textContent='동·관리 구역 구분명';label.style.cssText='display:block;font-size:12px;margin:16px 0 8px';const input=document.createElement('input');input.maxLength=50;input.placeholder='예: 별관, 2층 관리 구역';input.style.cssText='box-sizing:border-box;width:100%;padding:12px;border:1px solid #bbcddd;border-radius:9px;font-size:15px';label.append(input);const error=document.createElement('p');error.setAttribute('role','alert');error.style.color='#b42318';const submit=button('구분해서 등록',()=>{});submit.type='submit';form.append(label,error,submit);form.onsubmit=e=>{e.preventDefault();const area=input.value.trim();if(!area){error.textContent='구분명을 입력해 주세요.';input.focus();return;}finish({area});};
 const actions=document.createElement('div');actions.style.cssText='display:flex;gap:8px;margin-top:18px;flex-wrap:wrap';actions.append(button('다른 동·구역 별도 등록',()=>{form.hidden=false;input.focus();}),button('취소',()=>finish(null)));d.append(actions,form);d.addEventListener('cancel',e=>{e.preventDefault();finish(null);});document.body.append(d);d.showModal();d.querySelector('button')?.focus();
});};
