(()=>{
 const root=document.getElementById('manager-sidebar');if(!root)return;
 const tabs=[...root.querySelectorAll('[data-ms-tab]')];
 const track=root.querySelector('.ms-tabs');const indicator=document.createElement('span');indicator.className='ms-slide-indicator';indicator.setAttribute('aria-hidden','true');track.append(indicator);
 function slidePosition(){const i=tabs.findIndex(t=>t.getAttribute('aria-selected')==='true');track.style.setProperty('--tab-index',Math.max(0,i));track.style.setProperty('--tab-count',Math.max(1,tabs.length));}
 function step(delta){const i=tabs.findIndex(t=>t.getAttribute('aria-selected')==='true');const tab=tabs[(i+delta+tabs.length)%tabs.length];if(tab)open(tab.dataset.msTab);}
 root.querySelector('[data-slide-prev]')?.addEventListener('click',()=>step(-1));root.querySelector('[data-slide-next]')?.addEventListener('click',()=>step(1));
 let touch=null;root.addEventListener('touchstart',e=>{if(e.touches.length!==1||e.target.closest('input,select,textarea,button,a,summary')){touch=null;return;}touch={x:e.touches[0].clientX,y:e.touches[0].clientY};},{passive:true});root.addEventListener('touchend',e=>{if(!touch)return;const t=e.changedTouches[0],dx=t.clientX-touch.x,dy=t.clientY-touch.y;touch=null;if(Math.abs(dx)>65&&Math.abs(dx)>Math.abs(dy)*1.8)step(dx<0?1:-1);},{passive:true});root.addEventListener('touchcancel',()=>touch=null);

 function open(name){if(!tabs.some(t=>t.dataset.msTab===name))name=tabs[0]?.dataset.msTab;try{sessionStorage.setItem('manager-workspace-tab',name);}catch{}tabs.forEach(t=>{const active=t.dataset.msTab===name;t.setAttribute('aria-selected',String(active));t.tabIndex=active?0:-1;const panel=document.getElementById('ms-'+t.dataset.msTab);if(panel)panel.hidden=!active;});slidePosition();document.dispatchEvent(new CustomEvent('manager-tab-changed',{detail:{tab:name}}));}
 tabs.forEach((tab,i)=>{tab.addEventListener('click',()=>open(tab.dataset.msTab));tab.addEventListener('keydown',e=>{let next;if(e.key==='ArrowRight')next=(i+1)%tabs.length;if(e.key==='ArrowLeft')next=(i+tabs.length-1)%tabs.length;if(e.key==='Home')next=0;if(e.key==='End')next=tabs.length-1;if(next!==undefined){e.preventDefault();open(tabs[next].dataset.msTab);tabs[next].focus();}});});
 document.querySelectorAll('[data-ms-open]').forEach(el=>el.addEventListener('click',e=>{e.preventDefault();open(el.dataset.msOpen);root.scrollIntoView({behavior:'smooth',block:'nearest'});}));
 document.querySelector('[data-ms-copy]')?.addEventListener('click',async()=>{const code=document.querySelector('[data-ms-code]').textContent;const note=document.querySelector('[data-ms-copy-note]');note.classList.add('is-feedback');try{await navigator.clipboard.writeText(code);note.textContent='코드를 복사했습니다.';}catch{note.textContent='코드를 길게 누르거나 선택해서 복사해 주세요.';}});
 const rows=[...root.querySelectorAll('[data-ms-name]')];if(!document.getElementById('manager-approval-panel'))root.querySelector('#ms-search')?.addEventListener('input',e=>{const q=e.target.value.trim().toLocaleLowerCase();let visible=0;rows.forEach(row=>{row.hidden=!row.dataset.msName.toLocaleLowerCase().includes(q);if(!row.hidden)visible++;});root.querySelector('[data-ms-no-results]').hidden=visible>0||rows.length===0;});
 root.querySelectorAll('[data-ms-map]').forEach(button=>button.addEventListener('click',()=>{document.dispatchEvent(new CustomEvent('manager-map-focus',{detail:{uid:button.dataset.msMap}}));document.getElementById('map')?.scrollIntoView({behavior:'smooth',block:'center'});}));
 let saved;try{saved=sessionStorage.getItem('manager-workspace-tab');}catch{}
 open(saved||tabs.find(t=>t.getAttribute('aria-selected')==='true')?.dataset.msTab||'users');
})();

(()=>{const dialog=document.getElementById('manager-wallet-dialog'),button=document.querySelector('[data-wallet-open]');if(!dialog||!button)return;button.addEventListener('click',()=>dialog.showModal());dialog.querySelector('[data-wallet-close]').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});dialog.addEventListener('close',()=>button.focus());})();
