(()=>{
 let dialog,frame,lastFocus,dirty=false;
 function close(){try{if(frame.contentWindow.managerDraftCanLeave&&!frame.contentWindow.managerDraftCanLeave())return;}catch{}dialog.close();frame.src='about:blank';if(dirty){location.reload();return;}lastFocus?.focus();}
 document.addEventListener('click',e=>{const a=e.target.closest('a[data-address-open]');if(!a)return;const url=new URL(a.href,location.href);if(url.origin!==location.origin||url.pathname!=='/manager_addresses.php')return;e.preventDefault();lastFocus=a;dirty=false;
  if(!dialog){dialog=document.createElement('dialog');dialog.setAttribute('aria-label','거래처 기본정보 사전 등록');dialog.style.cssText='width:min(800px,calc(100% - 24px));height:min(820px,90dvh);max-height:90vh;padding:0;border:1px solid #dce4e8;border-radius:16px;box-shadow:0 24px 80px #122d4140';const style=document.createElement('style');style.textContent='dialog[data-address-dialog]{position:fixed!important;inset:0!important;margin:auto!important;transform:none!important;max-width:calc(100vw - 24px)!important}dialog[data-address-dialog]::backdrop{background:#12263770}';document.head.append(style);dialog.dataset.addressDialog='1';const bar=document.createElement('div');bar.style.cssText='display:flex;align-items:center;justify-content:space-between;padding:10px 16px;border-bottom:1px solid #e7ecef';const b=document.createElement('button');b.type='button';b.textContent='닫기 ×';b.style.cssText='border:0;background:#f0f4f5;color:#40535d;border-radius:6px;padding:7px 12px;cursor:pointer';b.addEventListener('click',close);const title=document.createElement('strong');title.textContent='거래처 관리';title.style.cssText='font:600 13px system-ui;color:#274139';bar.append(title,b);frame=document.createElement('iframe');frame.title='거래처 기본정보 사전 등록';frame.style.cssText='display:block;width:100%;height:calc(100% - 49px);border:0';dialog.append(bar,frame);document.body.append(dialog);dialog.addEventListener('cancel',e=>{e.preventDefault();close();});}
  dialog.querySelector('strong').textContent=url.searchParams.has('requests')?'새로운 연결 요청':url.searchParams.has('request')?'연결 요청 검토':'거래처 사전 등록';if(url.searchParams.has('requests'))dirty=true;frame.src=url.href;dialog.showModal();
 });
 window.addEventListener('message',e=>{if(e.origin===location.origin&&e.source===frame?.contentWindow&&e.data?.type==='manager-addresses-changed')dirty=true;});
})();
