(()=>{'use strict';if(window.proCollaboration)return;
const paid=document.currentScript?.dataset.pro==='1',manager=document.currentScript?.dataset.manager==='1';
const style=document.createElement('style');style.textContent=`
#proCollaborationDialog{box-sizing:border-box;position:fixed!important;inset:50% auto auto 50%!important;transform:translate(-50%,-50%);margin:0!important;width:min(480px,calc(100vw - 28px));max-height:calc(100dvh - 32px);padding:0;border:1px solid #dce7ec;border-radius:22px;background:white;color:#23374a;box-shadow:0 24px 90px #142b4350;overflow:auto;font:14px/1.7 system-ui}
#proCollaborationDialog::backdrop{background:#152c4266}#proCollaborationDialog .pc-body{padding:30px}#proCollaborationDialog .pc-close{position:absolute;right:15px;top:12px;border:0;background:transparent;font-size:24px;color:#718394;cursor:pointer}#proCollaborationDialog .pc-kicker{font-size:11px;font-weight:800;letter-spacing:.12em;color:#168ba2}#proCollaborationDialog h2{font-size:25px;line-height:1.5;letter-spacing:-.05em;margin:12px 0}#proCollaborationDialog p{color:#718090;margin:8px 0 20px}#proCollaborationDialog .pc-example{border:1px solid #e0e9ef;border-radius:12px;background:#f6f9fc;padding:15px;margin:20px 0}#proCollaborationDialog .pc-example small{display:block;color:#8090a0;font-size:11px}#proCollaborationDialog .pc-step{display:flex;align-items:center;justify-content:space-between;margin-top:7px;font-size:12px}#proCollaborationDialog .pc-step span{color:#16886e;background:#e6f5ee;border-radius:5px;padding:2px 7px}#proCollaborationDialog ul{padding-left:19px;color:#425c70;font-size:13px}#proCollaborationDialog li{margin:9px 0}#proCollaborationDialog .pc-price{display:flex;align-items:baseline;gap:7px;margin-top:23px}#proCollaborationDialog .pc-price b{font-size:25px}#proCollaborationDialog .pc-price small{color:#788896}#proCollaborationDialog .pc-start{display:block;margin-top:14px;padding:13px;text-align:center;border-radius:11px;background:#087e98;color:#fff;text-decoration:none;font-weight:750}#proCollaborationDialog :focus-visible{outline:3px solid #70bacb;outline-offset:3px}@media(max-width:480px){#proCollaborationDialog .pc-body{padding:26px 22px}}
`;document.head.append(style);
function open(){let owner=window;try{if(window.top!==window&&window.top.proCollaboration){window.top.proCollaboration.open();return;}}catch(e){}
 if(document.getElementById('proCollaborationDialog'))return;
 const previous=document.activeElement,dialog=document.createElement('dialog');dialog.id='proCollaborationDialog';dialog.setAttribute('aria-labelledby','pc-title');
 dialog.innerHTML='<button type="button" class="pc-close" aria-label="구독 안내 닫기">×</button><div class="pc-body"><span class="pc-kicker">PRO COLLABORATION</span><h2 id="pc-title">어려운 업무 기록,<br>담당매니저와 함께하세요.</h2><p>매니저 연결은 무료입니다.<br>PRO로 작성 도움을 요청하고 기록을 함께 관리하세요.</p><div class="pc-example"><small>협업 화면 예시</small><div class="pc-step">소방계획서 · 작성 도움 요청 <span>요청 접수</span></div><div class="pc-step">담당매니저가 답변 확인·작성 <span>작성 완료</span></div></div><ul><li>어려운 질문을 담당매니저에게 요청</li><li>같은 업무 기록을 함께 확인하고 작성·수정</li><li>요청한 항목의 처리 상태와 완료 여부 확인</li></ul><div class="pc-price"><b>연 59,000원</b><small>1년 이용</small></div><a class="pc-start" href="/subscribe_page.php" target="_top">PRO 구독 시작하기 →</a></div>';
 if(manager){const action=dialog.querySelector('.pc-start');action.removeAttribute('href');action.textContent='유저가 직접 PRO 구독을 시작할 수 있습니다.';}
 dialog.querySelector('.pc-close').onclick=()=>dialog.close();dialog.addEventListener('close',()=>{dialog.remove();if(previous?.isConnected)previous.focus();},{once:true});document.body.append(dialog);dialog.showModal();dialog.querySelector('.pc-close').focus();
}
window.proCollaboration={open};document.addEventListener('click',e=>{const a=e.target.closest('a[href]');if(!a||a.closest('#proCollaborationDialog')||e.ctrlKey||e.metaKey||e.shiftKey||e.altKey)return;const u=new URL(a.href,location.href);if(!paid&&u.origin===location.origin&&u.pathname==='/subscribe_page.php'){e.preventDefault();e.stopImmediatePropagation();open();}},true);
})();
